categories:
  homepage:
    title: Homepage
  pricing:
    title: Pricing
  hosting:
    title: Hosting
  product_ratings:
    title: Product ratings
  coupons:
    title: Coupons
  stock_management:
    title: Stock management
systems:
  magento:
    title: Magento
  shopify:
    title: Shopify
  shopware:
    title: Shopware
  woocommerce:
    title: WooCommerce
