categories:
  homepage:
    title: Homepage
  pricing:
    title: Pricing
  enterprise_support:
    title: Enterprise support
  extendable:
    title: Extendable
  plugin_store:
    title: Plugin store
  custom_themes:
    title: Custom themes
  hosting:
    title: Hosting
  programming_language:
    title: Programming language
  framework:
    title: Framework
  database:
    title: Database
  scheduled_publishing:
    title: Scheduled publishing
  signup_confirmation_email:
    title: Singup confirmation email
  emails_via_extensions:
    title: Sending emails via custom extensions
  2fa:
    title: 2FA
  rest_api:
    title: REST API
  graphql:
    title: GraphQL
  image_upload:
    title: Image upload
  image_transformations:
    title: Image transformations
  comments:
    title: Comments
  i18n_pages:
    title: Translations per page
  i18n_site_tree:
    title: Customizable site tree per translation
  search:
    title: Search
  review_workflow:
    title: Review workflow for editors
  content_versioning:
    title: Versioning for content
  authentication_mechanism:
    title: Authentication mechanism
  content_types:
    title: Content types

systems:
  adobe_experience_manager:
    title: Adobe Experience Manager
  contentful:
    title: Contentful
    logo: contentful.svg
  craft_cms:
    title: Craft CMS
    logo: craft_cms.svg
  datocms:
    title: DatoCMS
    logo: datocms.svg
  ghost:
    title: Ghost
    logo: ghost.png
  graphcms:
    title: GraphCMS
    logo: graphcms.svg
  grav:
    title: Grav
    logo: grav.svg
  kirby:
    title: Kirby
  squarespace:
    title: Squarespace
    logo: squarespace.svg
  statamic:
    title: Statamic
    logo: statamic.svg
  strapi:
    title: Strapi
    logo: strapi.svg
  typo3:
    title: TYPO3
    logo: typo3.png
  wix:
    title: Wix
  wordpress:
    title: WordPress
    logo: wordpress.png
  wordpresscom:
    title: WordPress.com
