categories:
  homepage:
    title: Homepage
  pricing:
    title: Pricing
  enterprise_support:
    title: Enterprise support
  technical_architecture:
    title: Technical architecture
    children:
      hosting:
        title: Hosting
      programming_language:
        title: Programming language
      framework:
        title: Framework
      database:
        title: Database
      content_types:
        title: Content types
        explanation: CMS which were made for specific purpose like creating a blog usually have pre-defined content types like pages or blog posts. On other CMS you can define the content types yourself.
  common_features:
    title: Common features
    children:
      search:
        title: Search
      search_suggestions:
        title: Search suggestions
      comments:
        title: Comments
      scheduled_publishing:
        title: Scheduled publishing
        explanation: A feature that let's you publish content automatically at a previously specified date and time.
      emails:
        title: Sending emails
        explanation: It's common that CMS and plugins only provide the functionality to send emails via external providers like Mailgun or similar.
      review_workflow:
        title: Review workflow for editors
      content_versioning:
        title: Versioning for content
  extendibility:
    title: Extendibility
    children:
      extendable:
        title: Extendable
      plugin_store:
        title: Extension/Plugin store
      custom_themes:
        title: Custom themes
  authentication:
    title: Authentication
    children:
      signup_confirmation_email:
        title: Singup confirmation email
      authentication_mechanism:
        title: Authentication mechanism
      2fa:
        title: 2FA
  apis:
    title: APIs
    children:
      headless:
        title: Headless or traditional
      rest_api:
        title: REST API
      graphql:
        title: GraphQL
  media:
    title: Media
    children:
      image_upload:
        title: Image upload
      image_transformations:
        title: Image transformations
  i18n:
    title: i18n
    children:
      i18n_pages:
        title: Translations per page
      i18n_site_tree:
        title: Customizable site tree per translation
  forms:
    title: Forms
    children:
      form_builder:
        title: Form builder
      form_submissions:
        title: Form submissions

systems:
  adobe_experience_manager:
    title: Adobe Experience Manager
  apostrophe:
    title: Apostrophe
  contentful:
    title: Contentful
    logo: contentful.svg
  craft_cms:
    title: Craft CMS
    logo: craft_cms.svg
  datocms:
    title: DatoCMS
    logo: datocms.svg
  ghost:
    title: Ghost
    logo: ghost.png
  graphcms:
    title: GraphCMS
    logo: graphcms.svg
  grav:
    title: Grav
    logo: grav.svg
  kirby:
    title: Kirby
  payload_cms:
    title: Payload CMS
  prismic:
    title: Prismic
  squarespace:
    title: Squarespace
    logo: squarespace.svg
  statamic:
    title: Statamic
    logo: statamic.svg
  storyblok:
    title: Storyblok
  strapi:
    title: Strapi
    logo: strapi.svg
  typo3:
    title: TYPO3
    logo: typo3.png
  wix:
    title: Wix
  wordpress:
    title: WordPress
    logo: wordpress.png
  wordpresscom:
    title: WordPress.com
